### ISSUE TITLE
GROS BUG using é in network SSID and maybe all utf8 stuff

### ISSUE THREAD

**Issue by HugoPoi** [YunoHost-Apps/hotspot_ynh#61]
Putting a network ssid with "é" complétely break yunohost throught command line installation

```bash
yunohost app install hotspot --force \
      --args "domain=$(urlencode "${settings[yunohost,domain]}")&path=/wifiadmin&wifi_ssid=$(urlencode "${settings[hotspot,wifi_ssid]}")&wifi_passphrase=$(urlencode "${settings[hotspot,wifi_passphrase]}")&firmware_nonfree=$(urlencode "${settings[hotspot,firmware_nonfree]}")"
# Then doing completely break yunohost app list
 yunohost app setting hotspot ip6_dns0 -v "${settings[hotspot,ip6_dns0]}"
```

```
root@testlime2:~# yunohost app list -i
Error: hotspot seems to be incorrectly installed
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 218, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 135, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 425, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 527, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 326, in app_list
    label = app_info_dict_raw['settings']['label']
KeyError: 'label'
```

## To reproduce
1. Put a SSID with an "é" in hypercube file
2. Install a brick
3. Apps list is breaked

## Notes
* https://stackoverflow.com/questions/4919889/is-there-a-standard-that-defines-what-is-a-valid-ssid-and-password

**Comment by alexAubin** [comment]
>Error: hotspot seems to be incorrectly installed

That seems to indicate an error happens during installation ..?

**Comment by HugoPoi** [comment]
I pretty sure I get "successful installation" and the problem seems triggered by  `yunohost app setting hotspot` but I will do some more extensive test to reproduce and add more logs

**Comment by hidrarga** [comment]
I just tried, I don't have the error, so I'm closing. Let me know if the issue still happens
